# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.srcs/sources_1/ip/ila_timer/ila_timer.xci
# IP: The module: 'ila_timer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.gen/sources_1/ip/ila_timer/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_timer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.gen/sources_1/ip/ila_timer/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.gen/sources_1/ip/ila_timer/ila_timer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.srcs/sources_1/ip/ila_timer/ila_timer.xci
# IP: The module: 'ila_timer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.gen/sources_1/ip/ila_timer/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.gen/sources_1/ip/ila_timer/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.gen/sources_1/ip/ila_timer/ila_timer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
