# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.runs/synth_1/rk_xcku5p.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param general.maxThreads 4
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku5p-ffvb676-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.cache/wt [current_project]
set_property parent.project_path /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/tommy/smolrv64/third_party/cvfpu/src/common_cells/include
  /home/tommy/smolrv64/inorder
  /home/tommy/smolrv64/src
} [current_fileset]
set_property verilog_define {MEM_BASEADDR=64'h70000000 PROBE_CORE INO_CORE SOC_BOOT_HEX=\"/home/tommy/smolrv64/src/mem.linehex\" PROBE_CLK_DIV=3 SMOLRV64_BUILD_STAMP=64'h20260814045449 SMOLRV64_GIT_COMMIT=32'h51e23520 SMOLRV64_GIT_DIRTY=1'b1 SMOLRV64_USE_XPM} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /home/tommy/smolrv64/third_party/cvfpu/src/common_cells/src/cf_math_pkg.sv
  /home/tommy/smolrv64/src/fp_unit.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_pkg.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_cast_multi.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_classifier.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_divsqrt_multi.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_divsqrt_th_32.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_divsqrt_th_64_multi.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_fma.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_fma_multi.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_noncomp.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_opgroup_block.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_opgroup_fmt_slice.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_rounding.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/fpnew_top.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/common_cells/src/lzc.sv
  /home/tommy/smolrv64/third_party/cvfpu/src/common_cells/src/rr_arb_tree.sv
  /home/tommy/smolrv64/src/smolrv64_cvfpu.sv
}
read_verilog -library xil_defaultlib {
  /home/tommy/smolrv64/src/aligner.v
  /home/tommy/smolrv64/src/alu.v
  /home/tommy/smolrv64/src/axi_single_beat_master.v
  /home/tommy/smolrv64/src/axi_two_master_arbiter.v
  /home/tommy/smolrv64/src/branch_unit.v
  /home/tommy/smolrv64/src/clint.v
  /home/tommy/smolrv64/src/crc32_d8.v
  /home/tommy/smolrv64/src/csr_file.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
  /home/tommy/smolrv64/src/ddr_hpm.v
  /home/tommy/smolrv64/src/ddr_line_axi.v
  /home/tommy/smolrv64/src/ddr_line_cdc.v
  /home/tommy/smolrv64/src/decode_exec.v
  /home/tommy/smolrv64/src/decode_fp.v
  /home/tommy/smolrv64/src/decode_operands.v
  /home/tommy/smolrv64/src/decode_slot.v
  /home/tommy/smolrv64/src/divider.v
  /home/tommy/smolrv64/src/eth_mac_rx.v
  /home/tommy/smolrv64/src/eth_mac_tx.v
  /home/tommy/smolrv64/src/eth_rx_engine.v
  /home/tommy/smolrv64/src/eth_tx_engine.v
  /home/tommy/smolrv64/src/exec_alu.v
  /home/tommy/smolrv64/src/fetch.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
  /home/tommy/smolrv64/src/gmii_to_rgmii.v
  /home/tommy/smolrv64/inorder/ino_cache.v
  /home/tommy/smolrv64/inorder/ino_core.v
  /home/tommy/smolrv64/inorder/ino_exec.v
  /home/tommy/smolrv64/inorder/ino_frontend.v
  /home/tommy/smolrv64/inorder/ino_l2_arbiter.v
  /home/tommy/smolrv64/inorder/ino_lsu.v
  /home/tommy/smolrv64/inorder/ino_regfile.v
  /home/tommy/smolrv64/inorder/ino_soc_top.v
  /home/tommy/smolrv64/src/mmu.v
  /home/tommy/smolrv64/src/mul3.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
  /home/tommy/smolrv64/third_party/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
  /home/tommy/smolrv64/src/plic.v
  /home/tommy/smolrv64/src/predictor.v
  /home/tommy/smolrv64/src/rgmii_rx.v
  /home/tommy/smolrv64/src/rgmii_tx.v
  /home/tommy/smolrv64/src/rs232rx.v
  /home/tommy/smolrv64/src/rs232tx.v
  /home/tommy/smolrv64/src/rvc_expand.v
  /home/tommy/smolrv64/src/sd_spi_host.v
  /home/tommy/smolrv64/src/smolrv64_async_fifo.v
  /home/tommy/smolrv64/src/smolrv64_plic_arbiter.v
  /home/tommy/smolrv64/src/smolrv64_sdpram.v
  /home/tommy/smolrv64/src/virtio_blk.v
  /home/tommy/smolrv64/src/virtio_mmio.v
  /home/tommy/smolrv64/src/virtio_net.v
  /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.srcs/rk_xcku5p.v
}
read_ip -quiet /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.srcs/sources_1/ip/ddr4_0/ddr4_0.xci
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/ip_1/par/ddr4_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_0/bd_9054_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_0/bd_9054_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_1/bd_9054_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_2/bd_9054_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_3/bd_9054_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_6/bd_9054_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_9/bd_9054_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/bd_0/ip/ip_10/bd_9054_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/bd_0/bd_9054_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/ip_0/ddr4_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/ip_0/ddr4_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/ddr4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/par/ddr4_0.xdc]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/ip_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/ddr4_0_ex.gen/sources_1/ip/ddr4_0/sw/calibration_0/Debug/calibration_ddr.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.srcs/rk_xcku5p.xdc
set_property used_in_implementation false [get_files /home/tommy/smolrv64/platforms/rk-xcku5p-f-v1.2/rk_xcku5p.srcs/rk_xcku5p.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top rk_xcku5p -part xcku5p-ffvb676-2-i -global_retiming on -control_set_opt_threshold 16
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rk_xcku5p.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file rk_xcku5p_utilization_synth.rpt -pb rk_xcku5p_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
