#!/usr/bin/env python3
"""Turn a Linux console font (PSF1 or PSF2, optionally gzipped) into a C array of the 95
printable ASCII glyphs, U+0020..U+007E, for the ROM monitor's screen console.

    tools/psf2c.py <font.psf[.gz]> [<LICENSE>] > workloads/monitor/font.h

The monitor's is Spleentt (github.com/tommythorn/spleentt-5x8-font, SpleenttMedium.psf), with its
LICENSE, which the header then carries. Glyphs are found through the font's Unicode table when
it has one, else by code point. Fonts up to 8 pixels wide: a glyph is `height` bytes, one per
row, MSB leftmost.
"""
import gzip
import struct
import sys

path = sys.argv[1]
data = (gzip.open if path.endswith('.gz') else open)(path, 'rb').read()
umap = {}
if data[:2] == b'\x36\x04':                                   # PSF1
    mode, height = data[2], data[3]
    count, width, off = (512 if mode & 1 else 256), 8, 4
    glyphs = [data[off + i * height: off + (i + 1) * height] for i in range(count)]
    if mode & 2:
        p, g = off + count * height, 0
        while g < count and p + 2 <= len(data):
            u = struct.unpack_from('<H', data, p)[0]; p += 2
            if u == 0xFFFF: g += 1
            elif u != 0xFFFE: umap.setdefault(u, g)
elif data[:4] == b'\x72\xb5\x4a\x86':                         # PSF2
    _, _, hdr, flags, count, size, height, width = struct.unpack_from('<8I', data, 0)
    glyphs = [data[hdr + i * size: hdr + (i + 1) * size] for i in range(count)]
    if flags & 1:
        p, g = hdr + count * size, 0
        while g < count and p < len(data):
            b = data[p]
            if b == 0xFF: g += 1; p += 1
            elif b == 0xFE: p += 1
            else:
                n = 1 if b < 0x80 else 2 if b < 0xE0 else 3 if b < 0xF0 else 4
                umap.setdefault(ord(data[p:p + n].decode('utf-8')), g); p += n
else:
    sys.exit(f'{path}: not a PSF font')
if width > 8:
    sys.exit(f'{path}: {width} pixels wide; at most 8 is supported')

print(f'// GENERATED by tools/psf2c.py from {path.split("/")[-1]}: do not edit.')
print(f'// U+0020..U+007E, {width}x{height}, one byte per row, MSB leftmost.')
if len(sys.argv) > 2:
    print('//')
    for line in open(sys.argv[2]).read().rstrip().split('\n'):
        print(('// ' + line).rstrip())
print(f'#define FONT_W {width}')
print(f'#define FONT_H {height}')
print(f'static const uint8_t font[95][{height}] = {{')
for c in range(0x20, 0x7F):
    g = glyphs[umap.get(c, c)]
    print('    { ' + ', '.join(f'0x{b:02x}' for b in g[:height]) + f' }},  // {chr(c)!r}')
print('};')
